"""Capture what the REAL driver puts on the panel, so the sim can be checked
against it instead of trusted.

Run this ON a board:

    mpremote connect COM9 run device_tests/golden_frame.py

It prints one `CASE <name> <base64>` line per case, where the payload is a
packed 1-bit-per-pixel bitmap of the top-left CAPTURE_W x CAPTURE_H corner.
tools/golden_frame.py renders the identical cases through MockCanvas and
compares.

Why this exists
---------------
The screenshots in this repo are what a reviewer looks at instead of buying
hardware, and for a while every one of them was wrong: MockCanvas substituted
a TrueType face for the device's built-in 8x8, so all 27 PNGs misrepresented
every glyph and nothing noticed. "The sim is faithful" was an assumption
sitting underneath the project's main review artefact.

This turns it into a measurement.

Bitmaps, not hashes, go over the wire. A hash tells you something differs; a
bitmap lets you see what, which is the difference between a five-minute fix
and an afternoon. It is also why the device does no hashing: every judgement
happens on the host, from bytes the host can inspect.

Monochrome, not colour, is deliberate. The device stores RGB565 and the mock
works in RGB888, so comparing colour would mean reconciling two quantisations
and would fail on rounding rather than on anything anyone cares about. Glyph
SHAPE is what diverged last time and shape is what this compares: a pixel is
set if it is not the background.
"""
import ubinascii

from seedwitness.drivers import cyd
from seedwitness.ui import fonts
from seedwitness.ui.canvas import HardwareCanvas

CAPTURE_W = 240
CAPTURE_H = 40
TEXT_X = 4
TEXT_Y = 4

# L covers only " +-0-9a-z" (see ui/fonts), so it gets a string it can spell.
# Asking it for uppercase would fall back and silently test the wrong face.
CASES = (
    ("XS", None, "seedwitness 0123"),
    ("S", "S", "seedwitness 0123"),
    ("M", "M", "seedwitness 0123"),
    ("L", "L", "0123 abcd"),
    # Not text. fill_circle is the one shape primitive the UI draws (die pips),
    # and two rasterisers would disagree pixel-for-pixel, so it is rendered
    # through theme.circle_spans on both sides and checked here like a glyph.
    ("PIPS", "pips", None),
    # blit_mask (the splash wordmark): pseudo-random bits, generated by the
    # same expression on both sides, so every bit position -- including the
    # padding bits past each row's width, which must be IGNORED -- is
    # exercised, not just the tidy strokes of the real wordmark.
    ("MASK", "mask", None),
)

MASK_W, MASK_H = 100, 30


def mask_case_data():
    stride = (MASK_W + 7) // 8
    return bytes((i * 73 + 41) & 0xFF for i in range(stride * MASK_H))


class _Recorder:
    """Intercepts Display.block() to build a bitmap of what was actually sent.

    draw_letter() and the scaled-text path both emit through block(), so
    wrapping that one method captures every rendering route the canvas can
    take without reimplementing any of them.
    """

    def __init__(self, display):
        self.display = display
        self.orig = display.block
        self.px = bytearray(CAPTURE_W * CAPTURE_H)

    def install(self):
        self.display.block = self._block

    def remove(self):
        self.display.block = self.orig

    def _block(self, x0, y0, x1, y1, data):
        w = x1 - x0 + 1
        i = 0
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                # RGB565, big-endian on the wire. Non-zero means "not the
                # background", which is all this comparison asks.
                hi = data[i]
                lo = data[i + 1]
                i += 2
                if 0 <= x < CAPTURE_W and 0 <= y < CAPTURE_H:
                    if hi or lo:
                        self.px[y * CAPTURE_W + x] = 1
        self.orig(x0, y0, x1, y1, data)
        _ = w


def pack(px):
    """1bpp, row-major, MSB first. Same packing as tools/golden_frame.py."""
    out = bytearray((CAPTURE_W * CAPTURE_H + 7) // 8)
    for i in range(CAPTURE_W * CAPTURE_H):
        if px[i]:
            out[i >> 3] |= 0x80 >> (i & 7)
    return out


def run():
    display = cyd.init_display()
    canvas = HardwareCanvas(display, None)
    faces = {"S": fonts.S, "M": fonts.M, "L": fonts.L}
    for name, face_key, text in CASES:
        canvas.fill((0, 0, 0))
        rec = _Recorder(display)
        rec.install()
        try:
            if face_key == "pips":
                for i, r in enumerate((3, 5, 8)):
                    canvas.fill_circle(30 + i * 60, 20, r, (255, 255, 255))
            elif face_key == "mask":
                canvas.blit_mask(4, 4, MASK_W, MASK_H, mask_case_data(),
                                 (255, 255, 255), (0, 0, 0))
            else:
                canvas.text(TEXT_X, TEXT_Y, text, (255, 255, 255),
                            font=faces.get(face_key) if face_key else None)
        finally:
            rec.remove()
        print("CASE %s %s" % (name, ubinascii.b2a_base64(pack(rec.px)).decode().strip()))
    print("DONE")


run()
