"""Flash-backed BIP39 wordlist: keeps 2048 words on the filesystem instead of
in RAM.

Why this exists: as a plain Python list the wordlist costs ~65KB of the
~148KB this app allocates -- by far its largest single consumer, on a board
with ~164KB of heap total. That left so little headroom that adding ~1KB of
bytecode was enough to make boot fail outright with a fragmentation
MemoryError, and it forced load-bearing import ordering in main.py.

embit already anticipates this: `wordlists/base.py`'s WordlistBase wraps any
object exposing get(i) / index(word) / len, which is how its `ubip39` variant
defers to a native module. That native module needs a custom firmware build,
which this project deliberately avoids -- so this provides the same interface
in pure Python, backed by a fixed-width binary file.

Format (generated by tools/build_mpy.sh from embit's own wordlist, so the two
cannot drift): 2048 records of WORD_WIDTH bytes, each an ASCII word padded
with NULs, in the wordlist's existing alphabetical order. Fixed width means
record i is simply at offset i * WORD_WIDTH -- no index needed.

Because the records are sorted, index() binary-searches in ~11 reads rather
than scanning. Lookup is O(log n) seeks against flash instead of O(1) against
RAM, which is a good trade here: the callers are a 12/24-word decode and a
keyboard prefix search, neither in a tight loop.
"""
WORD_WIDTH = 8  # longest BIP39 English word is 8 chars; asserted at build time
_PATH = "/bip39_words.bin"


class _FlashWordlist:
    def __init__(self, path, width):
        # held open for the life of the app: reopening per lookup would cost
        # far more than the seek, and there is nothing else contending for it
        self._f = open(path, "rb")
        self._w = width
        self._f.seek(0, 2)
        self.len = self._f.tell() // width

    def get(self, i):
        self._f.seek(i * self._w)
        return self._f.read(self._w).rstrip(b"\x00").decode()

    def index(self, word):
        """Binary search. Returns -1 when absent, which is the contract
        WordlistBase expects (it raises ValueError / returns False itself)."""
        lo = 0
        hi = self.len - 1
        while lo <= hi:
            mid = (lo + hi) >> 1
            found = self.get(mid)
            if found == word:
                return mid
            if found < word:
                lo = mid + 1
            else:
                hi = mid - 1
        return -1


WORDS = _FlashWordlist(_PATH, WORD_WIDTH)
