"""Flash-backed Spleen glyph data: keeps the three faces' bitmaps on the
filesystem instead of in RAM.

Why this exists: the three generated font modules (spleen_8x16/12x24/16x32)
hold 8,576 bytes of glyph rows, but importing them as .mpy cost ~25KB of
heap -- MicroPython copies every bytes object into RAM and charges module
overhead on top -- on a board whose UI finished booting with under 17KB
free. That was the margin the Generate Seed crash lived in. Same trick,
same reasons, as flash_wordlist.py next door: the bytes stay on flash and
are read on demand.

What ships where: seedwitness/ui/fonts/__init__.py (the Font class and the
rasteriser) is UNCHANGED and identical on device and desktop. Only the three
data modules are swapped at build time (see tools/build_mpy.sh) for shims
that resolve WIDTH/HEIGHT/ROW_BYTES/CHARS here, with DATA a _FlashData
reader instead of a bytes literal. Font.rows() slices DATA one glyph at a
time, and that is the only access pattern anywhere (Font.get_letter and
sim/mock_canvas both go through rows()), so supporting exactly that slice
is supporting everything.

Format of /fonts.bin (generated by tools/build_mpy.sh from the desktop
modules, round-tripped through THIS module's source at build time so the
shipped bytes cannot drift from the reviewable ones):

    b"SWF1"  u8 face_count  then per face, in ladder order S, M, L:
    u8 width  u8 height  u8 row_bytes  u16le nchars
    nchars bytes of CHARS (ASCII)
    nchars * height * row_bytes bytes of DATA, glyphs in CHARS order

CHARS stays in RAM (211 bytes across all faces) because Font.has() walks it
on every _fit_font ladder step; the glyph rows are what cost real memory
and they are only touched when a glyph is actually drawn.

Rendering cost, measured on the board: one seek+readinto of 16-72 bytes per
glyph, against a draw path whose pure-Python pixel loop takes ~3-4ms per
glyph -- the flash read is noise (see the report for the numbers).
"""
_PATH = "/fonts.bin"
_MAGIC = b"SWF1"


class _FlashData:
    """Read-only stand-in for a face module's DATA bytes.

    Font.rows() always slices exactly one glyph (height * row_bytes bytes),
    so that read lands in one buffer preallocated per face at import time:
    the steady-state draw path allocates nothing, which matters as much as
    the resident saving on a heap that fragments and is never compacted.
    The buffer is safe to share across calls because draw_letter() consumes
    each glyph fully (synchronous SPI write) before the next is fetched --
    the same reuse contract as Font's own scratch cell.
    """

    def __init__(self, f, base, size, glyph_bytes):
        self._f = f
        self._base = base
        self._size = size
        self._buf = bytearray(glyph_bytes)

    def __len__(self):
        return self._size

    def __getitem__(self, sl):
        start = sl.start
        n = sl.stop - start
        self._f.seek(self._base + start)
        if n == len(self._buf):
            self._f.readinto(self._buf)
            return self._buf
        return self._f.read(n)


def _load(path):
    # held open for the life of the app, like the wordlist readers: reopening
    # per glyph would cost far more than the seek
    f = open(path, "rb")
    if f.read(4) != _MAGIC:
        raise ValueError("fonts.bin: bad magic")
    count = f.read(1)[0]
    faces = []
    pos = 5
    for _ in range(count):
        f.seek(pos)
        hdr = f.read(5)
        width, height, row_bytes = hdr[0], hdr[1], hdr[2]
        nchars = hdr[3] | (hdr[4] << 8)
        chars = f.read(nchars).decode()
        glyph_bytes = height * row_bytes
        size = nchars * glyph_bytes
        faces.append((width, height, row_bytes, chars,
                      _FlashData(f, pos + 5 + nchars, size, glyph_bytes)))
        pos += 5 + nchars + size
    return faces


_FACES = _load(_PATH)


def face(i):
    """(WIDTH, HEIGHT, ROW_BYTES, CHARS, DATA) for face index i -- the shim
    modules unpack this straight into the names Font.__init__ reads."""
    return _FACES[i]
